
CREATE DATABASE IF NOT EXISTS nova_hotel
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE nova_hotel;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ad_soyad VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  telefon VARCHAR(20) NULL,
  sifre VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


ALTER TABLE users
  ADD COLUMN IF NOT EXISTS telefon VARCHAR(20) NULL AFTER email;


CREATE TABLE IF NOT EXISTS rezervasyonlar (
  id INT AUTO_INCREMENT PRIMARY KEY,
  musteri_adi VARCHAR(120) NOT NULL,
  oda_tipi VARCHAR(60) NOT NULL,
  giris_tarihi DATE NOT NULL,
  cikis_tarihi DATE NOT NULL,
  toplam_fiyat DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  durum VARCHAR(40) NOT NULL DEFAULT 'Beklemede',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

